openapi: 3.0.0
info:
  title: MyLife GPT Webhook Receiver API
  description: This API is for receiving webhooks from [MyLife's public Biographer Bot instance](https://chat.openai.com/g/g-QGzfgKj6I-mylife-biographer-bot).
  version: 1.0.0
servers:
  - url: https://4c87-73-149-210-124.ngrok-free.app/api/v1
    description: Endpoint for receiving stories from the MyLife Biographer Bot instance.
security:
  - bearerAuth: []
paths:
  /story:
    post:
      operationId: MyLifeBiographerStoryCreation
      summary: MyLife Biographer Bot will access this endpoint to generate a `bio-story` document in MyLife Cosmos.
      description: Endpoint for handling incoming registration webhook data from the MyLife GPT service.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              description: The `story` data sent by MyLife Biographer BOt.
              type: object
              required:
                - assistantType
                - memberKey
                - storySummary
              properties:
                assistantType:
                  default: MyLife-Biographer-Bot
                  description: The type of assistant that generated the story.
                  type: string
                memberKey:
                  description: Visitor enters memberKey and it is kept in GPT memory and sent with each request so that MyLife knows partition.
                  maxLength: 256
                  type: string
                storySummary:
                  description: MyLife Biographer Bot summary of identified `story`.
                  maxLength: 20480
                  type: string
      responses:
        "200":
          description: Webhook registration data received successfully.
post:
  operationId: MyLifeBiographerStoryCreation
  x-openai-isConsequential: false